### ISSUE TITLE
Add proof of soundness of counter example to `testable`

### ISSUE THREAD

**Issue by cipher1024** [cipher1024/slim_check#3]
As per @Kha's comment:

> @cipher1024 I'm assuming it wouldn't even be hard to prove the tool's soundness?

> @Kha With regards to the soundness, right now there's a type class testable for testable propositions, I believe the only thing I'd need to do is to return a proof of ¬ p along with any counter example produced. So the short answer is "no, I don't think it would be hard".

**Comment by Kha** [comment]
Wrong comment, I believe :) .

**Comment by cipher1024** [comment]
Haha! That's what I get for copy-pasting without looking :) But now I changed history, no one can tell I made such a silly mistake

**Comment by cipher1024** [comment]
I just changed the type `test_result` so that it carries a proof of `¬ p` when a test fail. Do you see it being more useful if the proof showed that the provided witness is the right one?

**Comment by Kha** [comment]
I'm assuming that the proofs are not very pretty to look at; showing internal consistency should be sufficient, I think.

**Comment by cipher1024** [comment]
That's one way to keep it extendible. We get instances of `testable` from `decidable` but if we wanted to go a different route, we could create `testable` instances to do model checking on various (finite / infinite) state machines. 

But I'm intrigued: how would you do it to make it prettier?

**Comment by Kha** [comment]
Oh, I don't believe proof terms are ever pretty or even interesting, as long as they typecheck :) .

**Comment by cipher1024** [comment]
That's true. I have feeling that you would have preferred a proof as one theorem stating that the whole thing is sound. Does that make sense?

I have been toying with a different idea though. Right now, the test result has a proof that it only fails if the proposition is false but I was thinking of adding a proof that the counterexample is valid:

```
class testable (p : Prop) :=
  (counterexample : Type)
  (showable_counterexample : has_to_string counterexample)
  (q : counterexample → Prop)
  (witness_validity : p ↔ (∀ x, q x))
  (run : gen (test_result q))
```

with 

```
inductive test_result {w : Type} (p : w → Prop)
-- ...
| failure :  ∀ x, ¬ p x → test_result
```

What do you think? It might get kind of tricky when witnesses lie in higher universes though.

**Comment by Kha** [comment]
I'm completely fine with your current approach. I'm not sure I understand your counterexample idea, but it indeed seems like something that you could only do on the meta level in general, i.e. constructing a proof at runtime.

**Comment by cipher1024** [comment]
I was actually wondering if I could execute part of the tactics inside the proof term. More specifically, I was thinking of creating a first random number generator seed in the tactic, and then use `whnf` on a goal of type `rand p` (where p would be the proof of something) just so that I can use the proof of `p` at the end of the computation and discharge the goal with it. Do you think that kind of use of `whnf` would be inefficient?
